<?xml version="1.0" encoding="utf-8"?><Database Name="belajarlinq" Class="ProgrammingDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IFANPRATAMA-PC\MSSQL2016;Initial Catalog=belajarlinq;Integrated Security=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="belajarlinqConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProductInfo" Member="ProductInfos">
    <Type Name="ProductInfo">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Design" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.delete_data" Method="delete_data">
    <Parameter Name="idProduct" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_data" Method="update_data">
    <Parameter Name="idProduct" Type="System.Int32" DbType="Int" />
    <Parameter Name="itemName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Design" Parameter="design" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UpdateDate" Parameter="updateDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_data" Method="insert_data">
    <Parameter Name="idProduct" Type="System.Int32" DbType="Int" />
    <Parameter Name="itemName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Design" Parameter="design" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ExpiryDate" Parameter="expiryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="InsertDate" Parameter="insertDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.show_data" Method="show_data">
    <ElementType Name="show_dataResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Design" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_data_by_id" Method="search_data_by_id">
    <Parameter Name="idProduct" Type="System.Int32" DbType="Int" />
    <ElementType Name="search_data_by_idResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Design" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>